stages:
  - Static Analysis
  - Test

before_script:
- apt-get update -qy
- apt-get install -y python-dev python3-pip
- pip install pip --upgrade
- pip install .

flake8:
  image: python:3.10
  stage: Static Analysis
  script:
    - pip install flake8
    - flake8
  allow_failure: true

pylint:
  image: python:3.10
  stage: Static Analysis
  script:
    - pip install pylint
    - pylint spynwave
  allow_failure: true

.testbase:
  script:
    - pip install .[tests]
    - pytest

python 3.8:
  extends: .testbase
  stage: Test
  image: python:3.8

python 3.9:
  extends: .testbase
  stage: Test
  image: python:3.9

python 3.10:
  extends: .testbase
  stage: Test
  image: python:3.10
